[project]
name = "vendorly"
version = "0.1.0"
description = "Educational project for learning the basic technology stack for python development"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.11",
    "google-genai>=1.7.0",
    "psycopg2>=2.9.10",
    "pydantic>=2.10.6",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.0.1",
    "sqlalchemy>=2.0.39",
    "uvicorn>=0.34.0",
]
